controller_list:
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - L0
      - L1
      - L2
      - L3
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - R0
      - R1
      - R2
      - R3
  - name: fake_end_left_controller
    type: $(arg fake_execution_type)
    joints:
      - L3
  - name: fake_end_right_controller
    type: $(arg fake_execution_type)
    joints:
      - R3
initial:  # Define initial robot poses per group
#  - group: left_hand
#    pose: home

  []